### ISSUE TITLE
Can't get ws281x LED to work

### ISSUE THREAD

**Issue by marierigal** [appleimperio/docker-hyperhdr#1]
Hi!

I'm using this Docker image to run HyperHDR on my Raspberry Pi 4 (thanks by the way) and I can't get my ws281x LED to work with this setup.

I know there are workarounds to make them work with [the standard HyperHDR installation on Linux](https://github.com/awawa-dev/HyperHDR/wiki/Installation#linux) by running this set of commands:

```bash
sudo systemctl disable --now hyperhdr@pi
sudo systemctl enable --now hyperhdr@root
```
See https://github.com/awawa-dev/HyperHDR/issues/52

It works well with this installation mode 👌 

But with the Docker image, I don't have access to `systemctl` in the container, so I'm kinda stuck here...
Although it should already run in root mode already 🤷‍♀️ 
Any idea of what might work?

Here is the error in HyperHDR logs:

```log
[LEDDEVICE_WS281X] Device disabled, device 'ws281x' signals error: 'Failed to open. Error message: mmap() failed'
```

And this is my Docker compose config:

```yaml
# docker-compose.yaml
version: '3'

services:
  hyperhdr:
    container_name: hyperhdr
    image: "nocturno/hyper-hdr:latest"
    restart: unless-stopped
    devices:
      - /dev/video0
    network_mode: host
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
    volumes:
      - /opt/hyperhdr/config:/config
```

I also tried with `PUID` and `PGID` set to `0` or  `privileged` set to `true` but with no luck.

Thanks for your help 🙏
